export const GameProviderKeys = [
  "every_matrix",
  "evolution",
  "expanse",
  "ezugi",
  "gameart",
  "habanero",
  "hacksaw_gaming",
  "inbet_games",
  "m_play",
  "netent",
  "pg_gamestop",
  "play_n_go",
  "pragmatic_play",
  "pragmatic_play_2",
  "playson",
  "playtech",
  "red_tiger",
  "relax_gaming",
] as const;
